// SPDX-FileCopyrightText: 2026 The Pion community <https://pion.ly>
// SPDX-License-Identifier: MIT

//go:build !js

// ffmpeg-receive is a simple application that shows how to receive media using Pion WebRTC and decode using FFmpeg.
package main

import (
	"bufio"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/asticode/go-astiav"
	"github.com/pion/interceptor"
	"github.com/pion/interceptor/pkg/intervalpli"
	"github.com/pion/rtp"
	"github.com/pion/rtp/codecs"
	"github.com/pion/webrtc/v4"
	"github.com/pion/webrtc/v4/pkg/media/samplebuilder"
)

// nolint:gocognit, cyclop
func main() {
	// Everything below is the Pion WebRTC API! Thanks for using it ❤️.

	// Create a MediaEngine object to configure the supported codec
	mediaEngine := &webrtc.MediaEngine{}
	if err := mediaEngine.RegisterDefaultCodecs(); err != nil {
		panic(err)
	}

	// Create a InterceptorRegistry. This is the user configurable RTP/RTCP Pipeline.
	// This provides NACKs, RTCP Reports and other features. If you use `webrtc.NewPeerConnection`
	// this is enabled by default. If you are manually managing You MUST create a InterceptorRegistry
	// for each PeerConnection.
	interceptorRegistry := &interceptor.Registry{}

	// Register a intervalpli factory
	// This interceptor sends a PLI every 3 seconds. A PLI causes a video keyframe to be generated by the sender.
	// This makes our video seekable and more error resilent, but at a cost of lower picture quality and higher bitrates
	// A real world application should process incoming RTCP packets from viewers and forward them to senders
	intervalPliFactory, err := intervalpli.NewReceiverInterceptor()
	if err != nil {
		panic(err)
	}
	interceptorRegistry.Add(intervalPliFactory)

	// Use the default set of Interceptors
	if err = webrtc.RegisterDefaultInterceptors(mediaEngine, interceptorRegistry); err != nil {
		panic(err)
	}

	// Create the API object with the MediaEngine
	api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine), webrtc.WithInterceptorRegistry(interceptorRegistry))

	// Create a new RTCPeerConnection
	peerConnection, err := api.NewPeerConnection(webrtc.Configuration{})
	if err != nil {
		panic(err)
	}
	defer peerConnection.Close() //nolint:errcheck

	peerConnection.OnTrack(onTrack)

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Printf("Connection State has changed %s \n", connectionState.String())
	})

	// Wait for the offer to be pasted
	offer := webrtc.SessionDescription{}
	decode(readUntilNewline(), &offer)

	// Set the remote SessionDescription
	err = peerConnection.SetRemoteDescription(offer)
	if err != nil {
		panic(err)
	}

	// Create an answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	// Sets the LocalDescription, and starts our UDP listeners
	err = peerConnection.SetLocalDescription(answer)
	if err != nil {
		panic(err)
	}

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete

	// Output the answer in base64 so we can paste it in browser
	fmt.Println(encode(peerConnection.LocalDescription()))

	select {}
}

// nolint:gocognit, cyclop
func onTrack(track *webrtc.TrackRemote, _ *webrtc.RTPReceiver) {
	if track.Kind() == webrtc.RTPCodecTypeAudio {
		return
	}

	codecName := strings.Split(track.Codec().MimeType, "/")[1]
	fmt.Printf("Track has started, of type %d: %s \n", track.PayloadType(), codecName)

	depacketizer, codecID := codecForName(codecName)
	builder := samplebuilder.New(10, depacketizer, track.Codec().ClockRate)

	codec := astiav.FindDecoder(codecID)
	if codec == nil {
		panic("FindDecoder returned nil")
	}

	codecContext := astiav.AllocCodecContext(codec)
	packet := astiav.AllocPacket()
	frame := astiav.AllocFrame()
	var pts int64
	if codecContext == nil {
		panic("Failed to AllocCodecContext")
	}
	if err := codecContext.Open(codec, nil); err != nil {
		panic(err)
	}
	defer codecContext.Free()
	defer packet.Free()
	defer frame.Free()

	for {
		rtpPacket, _, readErr := track.ReadRTP()
		if readErr != nil {
			if errors.Is(readErr, io.EOF) {
				return
			}
			panic(readErr)
		}

		builder.Push(rtpPacket)
		for sample := builder.Pop(); sample != nil; sample = builder.Pop() {
			packet.Unref()
			if err := packet.FromData(sample.Data); err != nil {
				panic(err)
			}

			packet.SetPts(pts)
			packet.SetDts(pts)
			pts++

			if err := codecContext.SendPacket(packet); err != nil {
				panic(err)
			}
			packet.Unref()

			for {
				if err := codecContext.ReceiveFrame(frame); err != nil {
					if errors.Is(err, astiav.ErrEof) || errors.Is(err, astiav.ErrEagain) {
						break
					}
					panic(err)
				}

				fmt.Printf("Decoded frame: pts=%d width=%d height=%d pixel_format=%s picture_type=%s sample_aspect_ratio=%s\n",
					frame.Pts(), frame.Width(), frame.Height(), frame.PixelFormat(),
					frame.PictureType(), frame.SampleAspectRatio(),
				)
				frame.Unref()
			}
		}
	}
}

func codecForName(codecName string) (rtp.Depacketizer, astiav.CodecID) {
	switch strings.ToLower(codecName) {
	case "av1":
		return &codecs.AV1Depacketizer{}, astiav.CodecIDAv1
	case "h264":
		return &codecs.H264Packet{}, astiav.CodecIDH264
	case "vp8":
		return &codecs.VP8Packet{}, astiav.CodecIDVp8
	case "vp9":
		return &codecs.VP9Packet{}, astiav.CodecIDVp9
	default:
		panic("Unhandled codec " + codecName) //nolint
	}
}

// Read from stdin until we get a newline.
func readUntilNewline() (in string) {
	var err error

	r := bufio.NewReader(os.Stdin)
	for {
		in, err = r.ReadString('\n')
		if err != nil && !errors.Is(err, io.EOF) {
			panic(err)
		}

		if in = strings.TrimSpace(in); len(in) > 0 {
			break
		}
	}

	fmt.Println("")

	return
}

// JSON encode + base64 a SessionDescription.
func encode(obj *webrtc.SessionDescription) string {
	b, err := json.Marshal(obj)
	if err != nil {
		panic(err)
	}

	return base64.StdEncoding.EncodeToString(b)
}

// Decode a base64 and unmarshal JSON into a SessionDescription.
func decode(in string, obj *webrtc.SessionDescription) {
	b, err := base64.StdEncoding.DecodeString(in)
	if err != nil {
		panic(err)
	}

	if err = json.Unmarshal(b, obj); err != nil {
		panic(err)
	}
}
